2020-08-18 10:04:26.671510: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-18 10:04:26.671543: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-08-18 10:04:29.354353: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-18 10:04:29.354383: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-18 10:04:29.354399: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (itchy): /proc/driver/nvidia/version does not exist
2020-08-18 10:04:29.354666: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-18 10:04:29.360141: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2000065000 Hz
2020-08-18 10:04:29.360254: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x61aced0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-18 10:04:29.360267: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-18 10:04:29.526435: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-08-18 10:04:31.611242: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
WARNING:tensorflow:From /Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
2020-08-18 10:04:32.750666: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32
2020-08-18 10:04:32.754827: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for trace.json.gz to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32/itchy.trace.json.gz
2020-08-18 10:04:32.758788: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32
2020-08-18 10:04:32.759297: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for memory_profile.json.gz to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32/itchy.memory_profile.json.gz
2020-08-18 10:04:32.764203: I tensorflow/python/profiler/internal/profiler_wrapper.cc:111] Creating directory: /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32Dumped tool data for xplane.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32/itchy.xplane.pb
Dumped tool data for overview_page.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32/itchy.overview_page.pb
Dumped tool data for input_pipeline.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32/itchy.input_pipeline.pb
Dumped tool data for tensorflow_stats.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32/itchy.tensorflow_stats.pb
Dumped tool data for kernel_stats.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold0_0818-1004/train/plugins/profile/2020_08_18_10_04_32/itchy.kernel_stats.pb

2020-08-18 10:06:54.710585: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-08-18 10:06:56.599403: I tensorflow/core/profiler/lib/profiler_session.cc:164] Profiler session started.
2020-08-18 10:06:57.833604: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57
2020-08-18 10:06:57.837790: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for trace.json.gz to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57/itchy.trace.json.gz
2020-08-18 10:06:57.840846: I tensorflow/core/profiler/rpc/client/save_profile.cc:176] Creating directory: /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57
2020-08-18 10:06:57.841352: I tensorflow/core/profiler/rpc/client/save_profile.cc:182] Dumped gzipped tool data for memory_profile.json.gz to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57/itchy.memory_profile.json.gz
2020-08-18 10:06:57.846329: I tensorflow/python/profiler/internal/profiler_wrapper.cc:111] Creating directory: /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57Dumped tool data for xplane.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57/itchy.xplane.pb
Dumped tool data for overview_page.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57/itchy.overview_page.pb
Dumped tool data for input_pipeline.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57/itchy.input_pipeline.pb
Dumped tool data for tensorflow_stats.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57/itchy.tensorflow_stats.pb
Dumped tool data for kernel_stats.pb to /Home/staff/mzehren/workspace/ADTOF/bin/../logs/fit/test_Limit:None_Fold1_0818-1006/train/plugins/profile/2020_08_18_10_06_57/itchy.kernel_stats.pb

2020-08-18 10:09:00.247920: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_ops_fused_impl.h:725 : Resource exhausted: OOM when allocating tensor with shape[100,23,166,32] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
Traceback (most recent call last):
  File "bin/trainModelTF.py", line 202, in <module>
    main()
  File "bin/trainModelTF.py", line 180, in main
    validation_steps=100
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1133, in fit
    return_dict=True)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1379, in evaluate
    tmp_logs = test_function(iterator)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 814, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/Home/staff/mzehren/workspace/ADTOF/venv/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[100,23,166,32] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu
	 [[node sequential_1/conv11/Relu (defined at bin/trainModelTF.py:180) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_test_function_8151]

Function call stack:
test_function

2020-08-18 10:09:00.375709: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
2020-08-18 10:09:00.376299: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
